In [ ]:
import sqlalchemy as db
import pandas as pd
from sqlalchemy import Column, Integer, ForeignKey, Table
from sqlalchemy.orm import relationship, declarative_base
from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.orm import declarative_base, sessionmaker
from sqlalchemy.ext.declarative import declarative_base

In [ ]:
engine = db.create_engine('mysql+pymysql://[username]:[password]@localhost/[database name]')
# ساخت یک انجین (نوع دیتابیس + کانکتور :// نام کاربری : رمز عبور @ هاست/ اسم دیتابیس)

In [83]:
try:
    conn = engine.connect()
    print('connected successfully')
except:
    print('could not connect to Database')

connected successfully

In [84]:
Base = declarative_base()

C:\Users\Asus\AppData\Local\Temp\ipykernel_5768\4196137762.py:1: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [85]:
class Team(Base):
    __tablename__ = 'teams'
    Team_ID = Column(Integer,primary_key = True, autoincrement=True)
    Team = Column(String(4))
    Team_Full_Name = Column(String(255))
    Location = Column(String(255))
    Seasons = Column(Integer)
    Years_Active = Column(String(255))
    Win = Column(Integer)
    Loss = Column(Integer)
    Playoff = Column(Integer)
    Championships = Column(Integer)
    league_champions = relationship('League_Champions',back_populates='team')
    mvp = relationship('MVP',back_populates='team')
    top50 = relationship('Top_50',back_populates='team')

class Player(Base):
    __tablename__ = 'players'
    Player_ID = Column(Integer, primary_key = True, autoincrement=True)
    Player_Name = Column(String(100))
    Position = Column(String(100))
    Shoots = Column(String(10))
    Experience = Column(Integer)
    height = Column(String(10))
    weight = Column(Integer)
    Birth_date = Column(String(50))
    Hometown = Column(String(100))
    Country_State = Column(String(100))
    league_champions = relationship('League_Champions',back_populates='players')
    mvp = relationship('MVP',back_populates='players')
    top50 = relationship('Top_50',back_populates='players')


class League_Champions(Base):
    __tablename__ = 'league_champions'
    ID = Column(Integer,primary_key = True,autoincrement=True)
    Player_ID = Column(Integer, ForeignKey('players.Player_ID'), index=True)
    Team_ID = Column(Integer, ForeignKey('teams.Team_ID'), index=True)
    Shirt_No = Column(String(5))
    Name = Column(String(100))
    Experience = Column(String(3))
    Season = Column(String(50))
    Team_abv = Column(String(4))
    team = relationship('Team',back_populates='league_champions')
    players = relationship('Player',back_populates='league_champions')

class MVP(Base):
    __tablename__ = 'mvp'
    ID = Column(Integer,primary_key = True,autoincrement=True)
    Player_ID = Column(Integer, ForeignKey('players.Player_ID'), index=True)
    Team_ID = Column(Integer, ForeignKey('teams.Team_ID'), index=True)
    Rank = Column(Integer)
    Name = Column(String(100))
    Team_abv = Column(String(4))
    Season = Column(String(50))
    team = relationship('Team',back_populates='mvp')
    players = relationship('Player',back_populates='mvp')

class Top_50(Base):
    __tablename__ = 'top50'
    ID = Column(Integer,primary_key = True,autoincrement=True)
    Player_ID = Column(Integer, ForeignKey('players.Player_ID'), index=True)
    Team_ID = Column(Integer, ForeignKey('teams.Team_ID'), index=True)
    Rank = Column(Integer)
    Name = Column(String(100))
    Team_abv = Column(String(4))
    Season = Column(String(50))
    team = relationship('Team',back_populates='top50')
    players = relationship('Player',back_populates='top50')

In [86]:
Base.metadata.create_all(engine)

In [87]:
df = pd.read_csv(r"C:\Users\Asus\Desktop\NBA\Players Information.csv")
df.to_sql("players", con=engine, if_exists="append", index=False)

df = pd.read_csv(r"C:\Users\Asus\Desktop\NBA\Team Information.csv")
df.to_sql("teams", con=engine, if_exists="append", index=False)

df = pd.read_csv(r"C:\Users\Asus\Desktop\NBA\League Champion.csv")
df.to_sql("league_champions", con=engine, if_exists="append", index=False)

df = pd.read_csv(r"C:\Users\Asus\Desktop\NBA\mvp.csv")
df.to_sql("mvp", con=engine, if_exists="append", index=False)

df = pd.read_csv(r"C:\Users\Asus\Desktop\NBA\top_50.csv")
df.to_sql("top50", con=engine, if_exists="append", index=False)

IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '1' for key 'players.PRIMARY'")
[SQL: INSERT INTO players (`Player_ID`, `Player_Name`, `Position`, `Shoots`, `Experience`, `Height`, `Weight`, `Birth_date`, `Hometown`, `Country_State`) VALUES (%(Player_ID)s, %(Player_Name)s, %(Position)s, %(Shoots)s, %(Experience)s, %(Height)s, %(Weight)s, %(Birth_date)s, %(Hometown)s, %(Country_State)s)]
[parameters: [{'Player_ID': 1, 'Player_Name': 'Markieff Morris', 'Position': 'Power Forward    ', 'Shoots': 'Right', 'Experience': 14, 'Height': '6\'9"', 'Weight': 245, 'Birth_date': 'September 2,\n 1989', 'Hometown': 'Philadelphia', 'Country_State': 'Pennsylvania'}, {'Player_ID': 2, 'Player_Name': 'Jack White', 'Position': 'Small Forward    ', 'Shoots': 'Right', 'Experience': 2, 'Height': '6\'7"', 'Weight': 225, 'Birth_date': 'August 5,\n 1997', 'Hometown': 'Traralgon', 'Country_State': 'Australia'}, {'Player_ID': 3, 'Player_Name': 'Bones Hyland', 'Position': 'Point Guard and Shooting Guard    ', 'Shoots': 'Right', 'Experience': 4, 'Height': '6\'2"', 'Weight': 173, 'Birth_date': 'September 14,\n 2000', 'Hometown': 'Wilmington', 'Country_State': 'Delaware'}, {'Player_ID': 4, 'Player_Name': 'Bobby Portis', 'Position': 'Power Forward and Center    ', 'Shoots': 'Right', 'Experience': 10, 'Height': '6\'10"', 'Weight': 250, 'Birth_date': 'February 10,\n 1995', 'Hometown': 'Little', 'Country_State': 'Arkansas'}, {'Player_ID': 5, 'Player_Name': 'Shai Gilgeous-Alexander', 'Position': 'Point Guard and Shooting Guard    ', 'Shoots': 'Right', 'Experience': 7, 'Height': '6\'6"', 'Weight': 200, 'Birth_date': 'July 12,\n 1998', 'Hometown': 'Toronto', 'Country_State': 'Ontario'}, {'Player_ID': 6, 'Player_Name': 'Khris Middleton', 'Position': 'Small Forward and Shooting Guard    ', 'Shoots': 'Right', 'Experience': 13, 'Height': '6\'7"', 'Weight': 222, 'Birth_date': 'August 12,\n 1991', 'Hometown': 'Charleston', 'Country_State': 'South Carolina'}, {'Player_ID': 7, 'Player_Name': 'JD Davison', 'Position': 'Shooting Guard and Point Guard    ', 'Shoots': 'Right', 'Experience': 3, 'Height': '6\'1"', 'Weight': 195, 'Birth_date': 'October 3,\n 2002', 'Hometown': 'Montgomery', 'Country_State': 'Alabama'}, {'Player_ID': 8, 'Player_Name': 'Jalen Williams', 'Position': 'Shooting Guard and Power Forward    ', 'Shoots': 'Right', 'Experience': 3, 'Height': '6\'6"', 'Weight': 220, 'Birth_date': 'April 14,\n 2001', 'Hometown': 'Denver', 'Country_State': 'Colorado'}  ... displaying 10 of 203 total bound parameter sets ...  {'Player_ID': 202, 'Player_Name': 'Rajon Rondo', 'Position': 'Point Guard    ', 'Shoots': 'Right', 'Experience': 16, 'Height': '6\'1"', 'Weight': 180, 'Birth_date': 'February 22,\n 1986', 'Hometown': 'Louisville', 'Country_State': 'Kentucky'}, {'Player_ID': 203, 'Player_Name': 'Tobias Harris', 'Position': 'Power Forward and Small Forward    ', 'Shoots': 'Right', 'Experience': 14, 'Height': '6\'8"', 'Weight': 226, 'Birth_date': 'July 15,\n 1992', 'Hometown': 'Islip', 'Country_State': 'New York'}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)